# -*- coding: utf-8 -*-
"""sample image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVfU-xM7l5R8NrCVFYMW97XAm-iqGJEO
"""

from PIL import Image, ImageDraw

# Create a 512x512 white canvas with a black rectangle
img = Image.new("RGB", (512, 512), "white")
draw = ImageDraw.Draw(img)
draw.rectangle([100, 100, 400, 400], fill="black")

img.save("sample_input.jpg")
img.show()